/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'veck' at '2015/7/15 上午 10:31' with Gradle 2.1
 *
 * @author veck, @date 2015/7/15 上午 10:31
 */
public class Hello {
  public static void main(String[] args){
    System.out.println("Hello World");
  }
}
