import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'veck' at '2015/7/15 上午 10:43' with Gradle 2.1
 *
 * @author veck, @date 2015/7/15 上午 10:43
 */
public class HelloTest {
    @Test public void testSomeLibraryMethod() {
        Hello classUnderTest = new Hello();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
